name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

    - name: Generate index.html with JSON embedded
      run: |
        jq -c . varhanici-data-merged.json > data.min.json
        # Insert into template directly
        awk 'NR==FNR{json=$0; next} {gsub(/__JSON_DATA__/, json)}1' data.min.json template.html > index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # current dir, includes index.html
          publish_branch: gh-pages
